/*
iDangero.us Chop Slider - Incredible Animated Slider
------------------------
Licensed under iDangero.us Commercial Regular license
------------------------
Version - 1.0
------------------------
More information on http://www.idangero.us/
*/
(function(b){b.fn.idChopSlider=function(a){function n(k){function i(){f.html("");e.html("");k=="next"?b(".activeSlide").next(j).length>0?b(".activeSlide").removeClass("activeSlide").next(".slide").addClass("activeSlide").show():(b(".activeSlide").removeClass("activeSlide"),b(j+":eq(0)").addClass("activeSlide").show()):b(".activeSlide").prev(j).length>0?b(".activeSlide").removeClass("activeSlide").prev(".slide").addClass("activeSlide").show():(b(".activeSlide").removeClass("activeSlide"),b(j+":last").addClass("activeSlide").show());
a.hideControls&&(d.nextTrigger.fadeIn(600),d.prevTrigger.fadeIn(600));d.loader.hide()}a.hideControls&&(d.nextTrigger.hide(),d.prevTrigger.hide());var h=b(j+".activeSlide");if(k=="next"){var l=h.next(j);l.length==0&&(l=b(j+":eq(0)"))}else l=h.prev(j),l.length==0&&(l=b(j+":last"));h.hide();d.loader.show();switch(a.type){case "vertical":for(var f=d.loader.find(".dummy-first"),e=d.loader.find(".dummy-last"),m=1;m<=a.vPieces;m++)f.append("<div ></div>"),e.append("<div ></div>");setTimeout(function(){e.show()},
a.dur1);setTimeout(function(){i()},a.dur1*1+a.vPieces*a.pieceDelay+a.xFadeDelay*1+a.dur2*1+a.dur3*1);f.children("div").each(function(){var c=b(this).index();e.children("div:eq("+c+")").css({width:g?a.width/a.vPieces:a.scaleX*a.width/a.vPieces,position:"absolute",top:a.yOffset,left:(a.width+a.xOffset*2)/a.vPieces*c-a.xOffset,height:g?a.height:a.scaleY*a.height,display:"none","background-image":"url("+l.find("img").attr("src")+")",backgroundPosition:-a.width/a.vPieces*c+"px top"});b(this).css({width:a.width/
a.vPieces,position:"absolute",top:0,left:a.width/a.vPieces*c,height:a.height,"background-image":"url("+h.find("img").attr("src")+")",backgroundPosition:-a.width/a.vPieces*c+"px top"});var i=g?{left:(a.width+a.xOffset*2)/a.vPieces*c-a.xOffset,top:a.yOffset}:{left:(a.width+a.xOffset*2)/a.vPieces*c-a.xOffset,top:a.yOffset,width:a.scaleX*b(this).width(),height:a.scaleY*b(this).height()};b(this).aCSS3({transform:"rotate(0deg) scaleY(1) scaleX(1)",delay:0,time:0}).delay(a.pieceDelay*c).animate(i,a.dur1,
function(){a.rotateSymmetric?e.find("div:eq("+c+")").aCSS3({transform:"rotate("+a.rotate+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:0,time:0}):e.find("div:eq("+c+")").aCSS3({transform:"rotate("+(-a.rotate+a.rotate*2*(b(this).index()+1)/a.vPieces)+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:0,time:0});var o=g?{left:a.width/a.vPieces*c,top:0}:{left:a.width/a.vPieces*c,top:0,width:g?"auto":a.width/a.vPieces,height:g?"auto":a.height};e.find("div:eq("+c+")").delay(a.xFadeDelay).fadeIn(a.dur2,
function(){f.children("div:eq("+c+")").hide();b(this).aCSS3({transform:"rotate(0deg) scaleY(1) scaleX(1)",time:a.dur3,delay:0})}).animate(o,a.dur3)});(function(b){setTimeout(function(){a.rotateSymmetric?f.children("div:eq("+b+")").aCSS3({transform:"rotate("+a.rotate+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:a.pieceDelay*b,time:a.dur1}):f.children("div:eq("+b+")").aCSS3({transform:"rotate("+(-a.rotate+a.rotate*2*(b+1)/a.vPieces)+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:a.pieceDelay*
b,time:a.dur1})},10)})(c)});break;case "horizontal":f=d.loader.find(".dummy-first");e=d.loader.find(".dummy-last").show();for(m=1;m<=a.hPieces;m++)f.append("<div ></div>"),e.append("<div ></div>");setTimeout(function(){e.show()},a.dur1);setTimeout(function(){i()},a.dur1*1+a.hPieces*a.pieceDelay+a.xFadeDelay*1+a.dur2*1+a.dur3*1);f.children("div").each(function(){var c=b(this).index();e.children("div:eq("+c+")").css({width:g?a.width:a.scaleX*a.width,position:"absolute",top:(a.height+a.yOffset*2)/a.hPieces*
c-a.yOffset,left:a.xOffset-a.xOffset*2/a.hPieces*c,height:g?a.height/a.hPieces:a.scaleY*a.height/a.hPieces,display:"none","background-image":"url("+l.find("img").attr("src")+")",backgroundPosition:"left "+-a.height/a.hPieces*c+"px"});b(this).css({width:a.width,position:"absolute",top:a.height/a.hPieces*c,left:0,height:a.height/a.hPieces,"background-image":"url("+h.find("img").attr("src")+")",backgroundPosition:"left "+-a.height/a.hPieces*c+"px"});var i=g?{left:a.xOffset-a.xOffset*2/a.hPieces*c,top:(a.height+
a.yOffset*2)/a.hPieces*c-a.yOffset}:{left:a.xOffset-a.xOffset*2/a.hPieces*c,top:(a.height+a.yOffset*2)/a.hPieces*c-a.yOffset,width:a.scaleX*b(this).width(),height:a.scaleY*b(this).height()};b(this).aCSS3({transform:"rotate(0deg) scaleY(1) scaleX(1)",delay:0,time:0}).delay(a.pieceDelay*c).animate(i,a.dur1,function(){a.rotateSymmetric?e.find("div:eq("+c+")").aCSS3({transform:"rotate("+a.rotate+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:0,time:0}):e.find("div:eq("+c+")").aCSS3({transform:"rotate("+
(-a.rotate+a.rotate*2*(b(this).index()+1)/a.vPieces)+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:0,time:0});var i=g?{left:0,top:a.height/a.hPieces*c}:{left:0,top:a.height/a.hPieces*c,width:a.width,height:a.height/a.hPieces};e.find("div:eq("+c+")").delay(a.xFadeDelay).fadeIn(a.dur2,function(){f.children("div:eq("+c+")").hide();b(this).aCSS3({transform:"rotate(0deg) scaleY(1) scaleX(1)",time:a.dur3,delay:0})}).animate(i,a.dur3)});(function(b){setTimeout(function(){a.rotateSymmetric?f.children("div:eq("+
b+")").aCSS3({transform:"rotate("+a.rotate+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:a.pieceDelay*b,time:a.dur1}):f.children("div:eq("+b+")").aCSS3({transform:"rotate("+(-a.rotate+a.rotate*2*(b+1)/a.vPieces)+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:a.pieceDelay*b,time:a.dur1})},10)})(c)});break;case "multi":f=d.loader.find(".dummy-first");e=d.loader.find(".dummy-last").show();for(m=1;m<=a.hPieces;m++)f.append("<div ></div>"),e.append("<div ></div>");setTimeout(function(){e.show()},
a.dur1);f.children("div").each(function(){var c=b(this).index();e.children("div:eq("+c+")").css({width:a.width,position:"absolute",top:a.height/a.hPieces*c,left:0,height:a.height/a.hPieces});for(var d=1;d<=a.vPieces;d++)b(this).append("<div ></div>"),e.children("div:eq("+c+")").append('<div style="display:none" ></div>');b(this).find("div").each(function(){var c=b(this).parent().index(),d=b(this).index();e.children("div:eq("+c+")").find("div:eq("+d+")").css({width:g?a.width/a.vPieces:a.scaleX*a.width/
a.vPieces,position:"absolute",top:a.yOffset*2*c/a.hPieces-a.yOffset,left:(a.width+a.xOffset*2)/a.vPieces*d-a.xOffset,height:g?a.height/a.hPieces:a.scaleY*a.height/a.hPieces,"background-image":"url("+l.find("img").attr("src")+")",backgroundPosition:-a.width/a.vPieces*d+"px "+-a.height/a.hPieces*c+"px"});b(this).css({width:a.width/a.vPieces,position:"absolute",top:0,left:a.width/a.vPieces*d,height:a.height/a.hPieces,"background-image":"url("+h.find("img").attr("src")+")",backgroundPosition:-a.width/
a.vPieces*d+"px "+-a.height/a.hPieces*c+"px"});var k=g?{left:(a.width+a.xOffset*2)/a.vPieces*d-a.xOffset,top:a.yOffset*2*c/a.hPieces-a.yOffset}:{left:(a.width+a.xOffset*2)/a.vPieces*d-a.xOffset,top:a.yOffset*2*c/a.hPieces-a.yOffset,width:a.scaleX*b(this).width(),height:a.scaleY*b(this).height()};b(this).aCSS3({transform:"rotate(0deg) scaleY(1) scaleX(1)",delay:0,time:0}).delay((c*a.vPieces/5+d)*a.pieceDelay).animate(k,a.dur1,function(){if(a.rotateSymmetric)e.children("div:eq("+c+")").find("div:eq("+
d+")").aCSS3({transform:"rotate("+a.rotate+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:0,time:0});else{var k=-(-a.rotate+a.rotate*2*(d+1)/a.vPieces);e.children("div:eq("+c+")").find("div:eq("+d+")").aCSS3({transform:"rotate("+k+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:0,time:0})}k=g?{left:a.width/a.vPieces*d,top:0}:{left:a.width/a.vPieces*d,top:0,width:a.width/a.vPieces,height:a.height/a.hPieces};e.children("div:eq("+c+")").find("div:eq("+d+")").delay(a.xFadeDelay).fadeIn(a.dur2,
function(){f.children("div:eq("+c+")").find("div:eq("+d+")").hide();b(this).aCSS3({transform:"rotate(0deg) scaleY(1) scaleX(1)",time:a.dur3,delay:0})}).animate(k,a.dur3,function(){(b(this).index()+1)*(b(this).parent().index()+1)==a.hPieces*a.vPieces&&i()})});(function(b,c){setTimeout(function(){if(a.rotateSymmetric)f.children("div:eq("+b+")").children("div:eq("+c+")").aCSS3({transform:"rotate("+a.rotate+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:(b*a.vPieces/5+c)*a.pieceDelay,time:a.dur1});
else{var d=-(-a.rotate+a.rotate*2*(c+1)/a.vPieces);f.children("div:eq("+b+")").children("div:eq("+c+")").aCSS3({transform:"rotate("+d+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+")",delay:(b*a.vPieces/5+c)*a.pieceDelay,time:a.dur1})}},10)})(c,d)});b(this).css({width:a.width,position:"absolute",top:a.height/a.hPieces*c,left:0,height:a.height/a.hPieces})})}}var d={},h=this;d.loader=b(a.loader);a.rotate=a.rotate||0;a.scaleY=a.scaleY>=0?a.scaleY:1;a.scaleX=a.scaleX>=0?a.scaleX:1;a.xOffset=a.xOffset||
0;a.yOffset=a.yOffset||0;a.hPieces=a.hPieces>0?a.hPieces:10;a.vPieces=a.vPieces>0?a.vPieces:10;a.dur1=a.dur1>=0?a.dur1:1E3;a.dur2=a.dur2>=0?a.dur2:600;a.dur3=a.dur3>=0?a.dur3:1E3;a.type=a.type||"vertical";a.rotateSymmetric=a.rotateSymmetric===!0||a.rotateSymmetric===!1?a.rotateSymmetric:!1;a.disableCSS3=a.disableCSS3===!0||a.disableCSS3===!1?a.disableCSS3:!1;a.pieceDelay=a.pieceDelay>=0?a.pieceDelay:50;a.xFadeDelay=a.xFadeDelay>=0?a.xFadeDelay:300;a.hideControls=a.hideControls===!0||a.hideControls===
!1?a.hideControls:!0;d.nextTrigger=b(a.nextTrigger);d.prevTrigger=b(a.prevTrigger);var j=a.slide||".slide";a.width=h.width();a.height=h.height();d.loader.css({left:h.offset().left,top:h.offset().top,position:"absolute","z-index":2E4,width:a.width,height:a.height,display:"none"});b(window).resize(function(){d.loader.css({left:h.offset().left,top:h.offset().top})});d.nextTrigger.click(function(a){a.preventDefault();n("next")});d.prevTrigger.click(function(a){a.preventDefault();n("prev")});var g=function(){var a=
(document.body||document.documentElement).style;return a.transition!==void 0||a.WebkitTransition!==void 0||a.MozTransition!==void 0||a.MsTransition!==void 0||a.OTransition!==void 0}()&&!a.disableCSS3;(function(a){a.fn.aCSS3=function(b){b.time=b.time||0;b.delay=b.delay||0;b.transform=b.transform||"";return this.each(function(){g&&a(this).css({"-webkit-transform":b.transform,"-webkit-transition-property":"-webkit-transform","-webkit-transition-duration":""+b.time/1E3+"s","-webkit-transition-delay":""+
b.delay/1E3+"s","-o-transform":b.transform,"-o-transition-property":"-o-transform","-o-transition-duration":""+b.time/1E3+"s","-o-transition-delay":""+b.delay/1E3+"s","-moz-transform":b.transform,"-moz-transition-property":"-moz-transform","-moz-transition-duration":""+b.time/1E3+"s","-moz-transition-delay":""+b.delay/1E3+"s","-ms-transition-property":"-ms-transform","-ms-transition-duration":""+b.time/1E3+"s","-ms-transition-delay":""+b.delay/1E3+"s","transition-property":"transform","transition-duration":""+
b.time/1E3+"s","transition-delay":""+b.delay/1E3+"s"})})}})(jQuery)}})(jQuery);